### ISSUE TITLE
Option --time-ranges always results in out of sync audio

### ISSUE THREAD

**Issue by cyperous** [DolbyLaboratories/dlb_mp4demux#1]
Option --time-ranges always results in out of sync audio when muxed back into mp4 using mp4muxer_release

**Comment by ShaoWeiguo** [comment]
Could you provide more information? like your cli, and signals.

**Comment by cyperous** [comment]
To be honest, I haven't used this utility in a very long time and now that dv is now supported in an MKV, I haven't had a use case to use it again.

I also noticed other updated since this issue was posted and I have not attempted any additional testing.  If you want to close this issue, that would be fine.

**Comment by ShaoWeiguo** [comment]
Thanks, @cyperous
